on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to run tests
    steps:
      - name: set output
        run: |
          echo "allure_url=https://green" >> "$GITHUB_OUTPUT"
      - name: show github_output
        run: |
          echo $GITHUB_OUTPUT