on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 10, 12, 14 ]
    name: A job to run tests
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: alekskulakov/allure-composite-action@branch_1
        with:
          install: true
          allure-endpoint: ${{ secrets.ALLURE_ENDPOINT }}
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: 7
          working-directory: './TestProject1'
          results: './bin/results'
          command: 'dotnet test'