on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to run tests
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: alekskulakov/allure-composite-action@v1.0.3
        with:
          install: true
          allure-endpoint: ${{ secrets.ALLURE_ENDPOINT }}
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: 7
          working-directory: './'
          results: './bin/results'
          command: 'dotnet tests --no-build'